#if defined _stock_officerspy_viewportpanelnames_included
	#endinput
#endif
#define _stock_officerspy_viewportpanelnames_included

#define PANEL_ALL			"all"		// all current panels
#define PANEL_ACTIVE		"active"	// current active panel			

#define PANEL_SCOREBOARD	"scores"
#define PANEL_OVERVIEW		"overview"
#define PANEL_CLASS			"class"
#define PANEL_TEAM			"team"
#define PANEL_SPECGUI		"specgui"	// passive spectator elements (top/bottom bars)
#define PANEL_SPECMENU		"specmenu"  // active spectator elements (options menus etc)
#define PANEL_INFO			"info"
#define PANEL_BUY			"buy"
#define PANEL_BUY_CT		"buy_ct"
#define PANEL_BUY_TER		"buy_ter"
#define PANEL_BUY_EQUIP_CT	"buyequip_ct"
#define PANEL_BUY_EQUIP_TER	"buyequip_ter"
#define PANEL_NAV_PROGRESS	"nav_progress"
#define PANEL_BUYPRESET_MAIN	"buypreset_main"
#define PANEL_BUYPRESET_EDIT	"buypreset_edit"
#define PANEL_INTRO			"intro"


#define PANEL_COMMENTARY_MODELVIEWER	"commentary_modelviewer"